### ISSUE TITLE
Please add support for attachments 

### ISSUE THREAD

**Issue by Feva** [dixudx/rtcclient#84]
First of all the library is excellent! Have been wanting something like this for a while.

I would like the ability to add, read and remove attachments. We add files to work items which I would like to add via a Python application I have been writing. The web interface I use is fine but I have an application that links to our ERP system for producing bespoke quotations. We will be using works items for tracking. I would like to be able to save emails and the like to work items.

Would this be possible?

Thanks for any response.

**Comment by dixudx** [comment]
@Feva I've already implemented this feature, supporting [addAttachment](http://rtcclient.readthedocs.io/en/development/workitem.html#rtcclient.workitem.Workitem.addAttachment) and [getAttachments](http://rtcclient.readthedocs.io/en/development/workitem.html#rtcclient.workitem.Workitem.getAttachments). Please try it. Thanks in advance.

**Comment by Feva** [comment]
@dixudx Thanks for this. Still a bit new to this so how do I install this now?
I originally used the "pip" command to install this but as this is a development branch in git I am unsure how to get this. 
I have tried to clone the git repo, checked out the development branch and then "python setup.py install" but get an error message:

C:\Temp\tmp\rtcclient>python setup.py
ERROR:root:Error parsing
Traceback (most recent call last):
  File "c:\temp\tmp\rtcclient\.eggs\pbr-0.11.1-py2.7.egg\pbr\core.py", line 109, in pbr
    attrs = util.cfg_to_args(path)
  File "c:\temp\tmp\rtcclient\.eggs\pbr-0.11.1-py2.7.egg\pbr\util.py", line 243, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "c:\temp\tmp\rtcclient\.eggs\pbr-0.11.1-py2.7.egg\pbr\hooks\__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "c:\temp\tmp\rtcclient\.eggs\pbr-0.11.1-py2.7.egg\pbr\hooks\base.py", line 27, in run
    self.hook()
  File "c:\temp\tmp\rtcclient\.eggs\pbr-0.11.1-py2.7.egg\pbr\hooks\metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "c:\temp\tmp\rtcclient\.eggs\pbr-0.11.1-py2.7.egg\pbr\packaging.py", line 654, in get_version
    raise Exception("Versioning for this project requires either an sdist"
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?
error in setup command: Error parsing C:\Temp\tmp\rtcclient\setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?

**Comment by dixudx** [comment]
@Feva It seems that you're installing using *tarball* instead of *git repo*. I've invoked [`pbr=True`](https://github.com/dixudx/rtcclient/blob/master/setup.py#L21). And this is why this exception occurs.

For installing and using this new feature, please clone the `development` branch,

```
$ git clone -b development https://github.com/dixudx/rtcclient
$ cd rtcclient
$ python setup.py install
```

After we've fully tested this feature, I will merge into master branch and package this library. Then you can install it simply by `pip install rtcclient`.

**Comment by Feva** [comment]
Sorry, tried that, still get an error:

C:\Temp\tmp\new>git clone -b development https://github.com/dixudx/rtcclient
Cloning into 'rtcclient'...
remote: Counting objects: 1285, done.
Receivi Total 1285 (delta 0), reused 0 (delta 0), pack-reused 1285R
Receiving objects: 100% (1285/1285), 263.43 KiB | 0 bytes/s, done.
Resolving deltas: 100% (867/867), done.

C:\Temp\tmp\new>cd rtcclient

C:\Temp\tmp\new\rtcclient>python setup.py install

Installed c:\temp\tmp\new\rtcclient\.eggs\pbr-0.11.1-py2.7.egg
ERROR:root:Error parsing
Traceback (most recent call last):
  File "c:\temp\tmp\new\rtcclient\.eggs\pbr-0.11.1-py2.7.egg\pbr\core.py", line 109, in pbr
    attrs = util.cfg_to_args(path)
  File "c:\temp\tmp\new\rtcclient\.eggs\pbr-0.11.1-py2.7.egg\pbr\util.py", line 243, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "c:\temp\tmp\new\rtcclient\.eggs\pbr-0.11.1-py2.7.egg\pbr\hooks\__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "c:\temp\tmp\new\rtcclient\.eggs\pbr-0.11.1-py2.7.egg\pbr\hooks\base.py", line 27, in run
    self.hook()
  File "c:\temp\tmp\new\rtcclient\.eggs\pbr-0.11.1-py2.7.egg\pbr\hooks\metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "c:\temp\tmp\new\rtcclient\.eggs\pbr-0.11.1-py2.7.egg\pbr\packaging.py", line 654, in get_version
    raise Exception("Versioning for this project requires either an sdist"
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?
error in setup command: Error parsing C:\Temp\tmp\new\rtcclient\setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?

C:\Temp\tmp\new\rtcclient>

**Comment by Feva** [comment]
@dixudx I have managed to install this by copying the PKG-INFO file (changed the internal Version number to 0.5.1 for the egg generation).
Looks good. I can get an Attachment object.

I would like to be able to download the actual file associated to that attachment as well. A bit like the changesets change object you have done. Would that be possible?

**Comment by dixudx** [comment]
@Feva Great. If you have already get an `Attachment` object, you can get the attachment url by visiting `attachment_obj.content`. The actual attachment file can by successfully downloaded through this url.

**Comment by Feva** [comment]
@dixudx I'll give that a go. 

It would be nice to have a helper method built in to do this, similar to the Change._fetchFile code which appears directly above the Attachment class in the models.py file. Or is that just needs from special cases where multiple files are referenced?

**Comment by dixudx** [comment]
@Feva Sorry for missing downloading method. Already added in [commit 6f4d4712](https://github.com/dixudx/rtcclient/commit/6f4d4712a983a0e91ee0f2c7346dbbd56f678c48#diff-a527ecb8834aedcb695e7bbbcd4b9752R326). Thanks for your reminding.

**Comment by Feva** [comment]
@dixudx Thanks for this. It sort of works in that it knows your are requesting a file. However, not sure how our system has been configured as the content returned is an XML response message regarding safeguards against malicious websites.

Is this a configuration of our RTC system or something you need to know about?

 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
		<title>Accessing content directly</title>
		<link rel="stylesheet" type="text/css" href="/ccm/web/com.ibm.team.repository.web/ui/oauth/templates/Authorize.css" />
	</head>
	<body>	
		<div class="boxDiv">
			
			<div class="content">
				You have followed a direct link to content hosted in a Jazz server.  This page has been presented to ensure that a malicious website cannot use cleverly crafted content to circumvent security. If you would like to access the content, please use the link below.
			</div>
			<div class="nav">
				<a style="float:right" href="http://rtc/ccm/resource/content/_tw3jgDCkEeepA7Vl_9LA0Q">Download content</a>
			</div>
		</div>
	</body>
</html>

**Comment by dixudx** [comment]
@Feva However it works well in my environment.

* Would you mind to download the file from  `attachment_obj.url` or `attachment_obj.content` (by [modifing rtcclient/models.py#L335](https://github.com/dixudx/rtcclient/blob/development/rtcclient/models.py#L335))?

* Or try to add a new param `allow_redirects=True` for `requests.get(...)`

**Comment by Feva** [comment]
@dixudx I don't really mind how it's done. Just would like to be able to download the attachment.
I have read a few places on the internet where they say it's not possible. So if you can do this it would be brilliant.

I noticed that if you manually run the content URL you get the message in the browser with a link to click. Click that and it gets saved but under a random named file. If you have logged out through the browser and then run the link, you are prompted to log in again and it automatically assumes that you are downloading the file. Bit strange.

**Comment by dixudx** [comment]
@Feva When you've got an `attachment_obj`, you can get the file name by visiting `attachment_obj.title`.

I cannot visit your environment, so I need your help to identify the reasons. What I really mean is that you should try below attempts,

1. When you've got an `attachment_obj`, please print out `attachment_obj.url` and `attachment_obj.content`, and compare this two urls that which one works;

2. If `attachment_obj.url` works, please modify [rtcclient/models.py#L335 in your site-packages folder](https://github.com/dixudx/rtcclient/blob/development/rtcclient/models.py#L335) from `self.content` to `self.url`; see what happens;

3. If still not works, please try to allow url redirecting by modifying [rtcclient/models.py#L335-L337](https://github.com/dixudx/rtcclient/blob/development/rtcclient/models.py#L335-L337) to 

```python
resp = requests.get(self.content,
                    verify=False,
                    allow_redirects=True,
                    headers=self.rtc_obj.headers)
```

**Comment by dixudx** [comment]
@Feva Actually it is not strange at all. When you logged out the system, related cookies disappeared. That's why you are prompted to log in again.

For testing, you just need to login the system once and do not log out. Then you visit those downloading urls to see which one works.

**Comment by Feva** [comment]
@dixudx OK, here we are:

URL: http://rtc/ccm/resource/itemOid/com.ibm.team.workitem.Attachment/_txBUizCkEeepA7Vl_9LA0Q
CONTENT: http://rtc/ccm/resource/content/_tw3jgDCkEeepA7Vl_9LA0Q

They are different.

Enter the URL into a web browser and you get prompted to save the file as the correct filename.
Enter the CONTENT into a web browser and you get the page about malicious web stuff.

Change line 335:

        resp = requests.get(self.url,

This now saves a file but it contains the following:

<?xml version="1.0" encoding="UTF-8"?><rtc_cm:Attachment xmlns:rtc_cm="http://jazz.net/xmlns/prod/jazz/rtc/cm/1.0/" rdf:about="http://rtc/ccm/resource/itemOid/com.ibm.team.workitem.Attachment/_txBUizCkEeepA7Vl_9LA0Q" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:dc="http://purl.org/dc/terms/">
<dc:identifier>8395</dc:identifier>
<dc:title>Software Services - Story 67315 Sales Forecasts Sapphire Application Version 2.docx</dc:title>
<dc:description>Software Services - Story 67315 Sales Forecasts Sapphire Application Version 2.docx</dc:description>
<dc:format>application/vnd.openxmlformats-officedocument.wordprocessingml.document</dc:format>
<rtc_cm:contentLength>1008219</rtc_cm:contentLength>
<dc:created>2017-05-04T09:36:06.216Z</dc:created>
<dc:creator rdf:resource="http://rtc/jts/users/rjw"/>
<dc:modified>2017-05-04T09:36:06.216Z</dc:modified>
<rtc_cm:modifiedBy rdf:resource="http://rtc/jts/users/rjw"/>
<rtc_cm:content rdf:resource="http://rtc/ccm/resource/content/_tw3jgDCkEeepA7Vl_9LA0Q"/>
</rtc_cm:Attachment>

Add the allow_redirects in still gives me a file with the above.

As a side note if I try:

webbrowser.open(attachment.url)

I get the standard windows save window so can save the file. Bit clunky but partly there for the time being.

**Comment by dixudx** [comment]
@Feva The url of `attachment_obj.content` *http://rtc/ccm/resource/content/_tw3jgDCkEeepA7Vl_9LA0Q* is exactly the same with

```html
<div class="nav">
	<a style="float:right" href="http://rtc/ccm/resource/content/_tw3jgDCkEeepA7Vl_9LA0Q">Download content</a>
</div>
```

Which means `attachment_obj.content` is the right url for downloading.

One noticeable thing is `dc:format`. The format you're using is `application/vnd.openxmlformats-officedocument.wordprocessingml.document`. However what I am testing against is `application/octet-stream`. I think this may be the bug. I will try to test this tomorrow.

And of course your current attachment file is not uploaded using [ addAttachment  in rtcclient/workitem.py#L760](https://github.com/dixudx/rtcclient/blob/development/rtcclient/workitem.py#L760). So would you mind using this function to upload a plain text file for testing ?

**Comment by dixudx** [comment]
@Feva Yes, you're right. It seems impossible to directly download the file through url. And this has nothing to do with *headers* or *file format*. Sorry for misleading you.

I guess this is caused by **htaccess**, which prevents downloading directly.

But uploading attachments still work.

**Comment by Feva** [comment]
@dixudx I think we have come to the same conclusion.
I can download the file via the webbrowser.open(attachment.url) so I have a means of getting the data.
To auto download would appear to be a big issue.
At this stage I think this can be left until IBM add functionality for this in the REST API.
Are you going to remove the download method from the Attachment class?

**Comment by dixudx** [comment]
@Feva Yeah, currently we have no other better ways.

I've already removed method `downloadFile` from `Attachment` class.

**Comment by Feva** [comment]
@dixudx Thanks for doing the work so far. I will start using this when I have free time at work.

**Comment by dixudx** [comment]
@Feva Already released `0.6.0`. You can install directly by `pip install -U rtcclient`. Thanks.

**Comment by rajapauldeloitte** [comment]
Hi,

I guess I also want to download the attachment and get the attachment binary content.

is there no way of doing it, i tried the webbrowser.open(). it's working.

i need to know if there are any other ways possible
